# Generated by Django 3.2.3 on 2021-05-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.SlugField(unique=True, verbose_name='line_id')),
                ('line_icon_url', models.URLField(verbose_name='line_icon_url')),
                ('line_name', models.CharField(max_length=20, verbose_name='line_name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineprofile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
