# Generated by Django 3.2.3 on 2021-05-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calliope_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='line_icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='line_icon_url'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='line_id',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='line_id'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='line_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='line_name'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
