# Generated by Django 3.2.4 on 2021-06-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calliope_web', '0007_auto_20210601_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bss',
            old_name='created_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bss',
            old_name='updated_datetime',
            new_name='updateded_at',
        ),
    ]
