# Generated by Django 3.2.4 on 2021-06-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calliope_web', '0008_auto_20210609_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bss',
            old_name='updateded_at',
            new_name='updated_at',
        ),
    ]
